Add windows test
fmoral2/rke2 pull request #1
Opened 2023-06-27 20:39 UTC by mdrahman-suse

#### Proposed Changes ####

#### Types of Changes ####

#### Verification ####

#### Linked Issues ####

#### Further Comments ####

2023-06-28 14:22 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +		ips :=  strings.Split(res, " ") //e2e.PodIPsUsingLabel(kubeConfigFile, "app=client")
comment not needed

2023-06-28 14:23 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +		cmd := fmt.Sprintf(`kubectl get pods -l %s -o=jsonpath='{range .items[*]}{.status.podIPs[*].ip}{" "}{end}' --kubeconfig=%s`, label, shared.KubeConfigFile)
this line  is exceding the limit . Should be break something like `cmd := fmt.Sprintf(`kubectl get pods -l %s -o=jsonpath='{range .items[*]}{.status.podIPs[*].ip}{" "}{end}' + 
 --kubeconfig=%s`, label, shared.KubeConfigFile)`

2023-06-28 14:24 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +func ValidatePodIPByLabel(label string, ip string) {
if your 2 params here are string you can declare the type only once like : 

`(label, ip string)`

2023-06-28 14:44 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +		return ips[0]
is always the first IP only that we should validate here in this assertion ?

2023-06-28 14:47 UTC, fmoral2 commented on tests/acceptance/core/service/factory/cluster.go
> +	NumWinAgents  	int
can we move this to line 20 to group windowns stuff ?   like 

`type Cluster struct {
	Status     		string
	ServerIPs  		string
	AgentIPs   		string
	WinAgentIPs		string
        NumWinAgents  	int
	NumServers 		int
	NumAgents  		int
}`

2023-06-28 14:50 UTC, fmoral2 commented on tests/acceptance/core/service/factory/cluster.go
> +	NumWinAgents, err := strconv.Atoi(terraform.GetVariableAsStringFromVarFile(g, varDir, "no_of_windows_worker_nodes"))
this line is exceding the limit , if you can break the the other above also!  please

2023-06-28 14:50 UTC, fmoral2 commented on tests/acceptance/core/service/factory/cluster.go
> +		WinAgentIPs: WinAgentIPs,
same here as https://github.com/fmoral2/rke2/pull/1/files#r1245348202

2023-06-28 15:05 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	defer func() {
why is this on a defer func ? 


if the Nodes func fails we should know that as earlier as possible right ?  which with the defer func will not happen.

2023-06-28 15:21 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +func ValidatePodIPByLabel(label string, ip string) {
what you think to try something like: `func ValidatePodIPByLabel(labels []string, ip string) {
	// Wait for the applied pod to have an IP
	Eventually(func() error {
		for label := range labels {
			if len(labels) > 0 {
				cmd := fmt.Sprintf(`kubectl get pods -l %s -o=jsonpath='{range .items[*]}{.status.podIPs[*].ip}{" "}{end}' --kubeconfig=%s`, labels[label], shared.KubeConfigFile)
				res, _ := shared.RunCommandHost(cmd)
				ips := strings.Split(res, " ")
				if len(ips) > 0 && strings.Contains(ips[0], ip) {
					return nil
				}
			}
		}
		return nil
	}, "120s", "10s").Should(Succeed(), fmt.Errorf("failed to validate expected: %s on %s", ip, labels))
}
`


in this way we can call this func only once on the test and be more dinamic.

2023-06-28 15:24 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	defer shared.ManageWorkload("delete","pod_client.yaml")
this defer we are using on the calling of the test because there you have flexibilty to call it or not ( depending on your use case )  if you add in here you are kind of "hard coding" this information

2023-06-28 15:25 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	assert.ValidatePodIPByLabel("app=client","10.42")
as commented on here - https://github.com/fmoral2/rke2/pull/1/files#r1245395626 

if you have a way to call yours labels just once it would be nice and cleaner. 

and the here u can do somehing like : 

```
func TestInternodeConnectivity() {
	shared.ManageWorkload("apply", "pod_client.yaml")
	shared.ManageWorkload("apply", "windows_app_deployment.yaml")
	assert.ValidatePodIPByLabel([]string{"app=client,app=windows-app"}, "10.42")
	testServiceCrossNodeCommunication()
}
```

2023-06-28 15:32 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	}, "120s", "3s").Should(ContainSubstring("Welcome to PSTools for K8s Debugging"), fmt.Errorf("failed cmd: %s",cmd))
line exciding limit - 

here you think we should assert this whole substring ?  `Welcome to PSTools for K8s Debugging` 
because if something change on this string our test fails.

2023-06-28 15:32 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	cmd := `sonobuoy run --kubeconfig=` + shared.KubeConfigFile + ` --plugin my-sonobuoy-plugins/mixed-workload-e2e/mixed-workload-e2e.yaml --aggregator-node-selector kubernetes.io/os:linux --wait`
line exciding limit -

2023-06-28 15:32 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	fmt.Println(cmd)
why this print here ?

2023-06-28 15:36 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +func TestInternodeConnectivity() {
here we should be clear that is a testing inter nodes for windows !

2023-06-28 15:37 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	res, err := shared.RunCommandHost(cmd)
add some spaces in your code , to be clear which block does what ...like : 
```
func TestSonobuoyMixedOS() {
	shared.InstallSonobuoy()
	cmd := `sonobuoy run --kubeconfig=` + shared.KubeConfigFile + ` --plugin my-sonobuoy-plugins/mixed-workload-e2e/mixed-workload-e2e.yaml --aggregator-node-selector kubernetes.io/os:linux --wait`
	res, err := shared.RunCommandHost(cmd)
	Expect(err).NotTo(HaveOccurred(), "failed output: "+res)

	cmd = `sonobuoy retrieve --kubeconfig=` + shared.KubeConfigFile
	testResultTar, err := shared.RunCommandHost(cmd)
	Expect(err).NotTo(HaveOccurred(), "failed cmd: "+cmd)

	cmd = "sonobuoy results " + testResultTar
	res, err = shared.RunCommandHost(cmd)
	Expect(err).NotTo(HaveOccurred(), "failed cmd: "+cmd)
	Expect(res).Should(ContainSubstring("Plugin: mixed-workload-e2e\nStatus: passed\n")) 

```

2023-06-28 15:41 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	fmt.Println("\n***********************************\n")
extra \n in the end. 
this func already do that automatically in the end.

Or do you want to break 2 lines?

2023-06-28 15:41 UTC, fmoral2 commented on tests/acceptance/core/testcase/pod.go
> +	fmt.Println("\n***********************************\n")
extra \n in the end. 
this func already do that automatically in the end.

Or do you want to break 2 lines?

2023-06-28 15:43 UTC, fmoral2 commented on tests/acceptance/core/testcase/pod.go
> +		fmt.Printf("Cluster pods\n")
can you add something like " : "  after the work pods?  or something else just to be more clear
 fmt.Printf("Cluster pods:\n")

2023-06-28 15:45 UTC, fmoral2 commented on tests/acceptance/entrypoint/mixedoscluster/mixedoscluster_suite_test.go
> +func TestClusterCreateSuite(t *testing.T) {
Add a more descriptive name for the test. Specifiyng also that is for windows

2023-06-28 16:02 UTC, fmoral2 commented on tests/acceptance/shared/cluster.go
> +// ManageWorkload applies or deletes a workload based on the action: create or delete.
correct also the comment here `create or delete.`

2023-06-28 16:03 UTC, fmoral2 commented on tests/acceptance/shared/cluster.go
> +func InstallSonobuoy() {
add some space on your func to separete concerns

2023-06-28 16:05 UTC, fmoral2 commented on tests/acceptance/shared/cluster.go
> +// Installs sonobuoy for mixed os validaion.
The name of the func on the doc should follow the same pattern. 
```

// InstallSonobuoy Installs sonobuoy for mixed os validaion.
func InstallSonobuoy() {

```

2023-06-28 16:05 UTC, fmoral2 commented on tests/acceptance/shared/cluster.go
empty extra line here

2023-06-28 16:13 UTC, fmoral2 commented
Its missing the makefile command to run the test and also add the test on docker run!!

2023-06-28 16:14 UTC, fmoral2 requested changes
.

2023-06-28 16:48 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +// Deploys services in the cluster and validates communication between nodes
func name msising on the doc

2023-06-28 16:49 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +
extra empty line

2023-06-28 16:56 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	cmd := `sonobuoy run --kubeconfig=` + shared.KubeConfigFile + ` --plugin my-sonobuoy-plugins/mixed-workload-e2e/mixed-workload-e2e.yaml --aggregator-node-selector kubernetes.io/os:linux --wait`
those places were you use backtick  is there a reason? 

normally we use that in raw string literals. Which can and cannot be the case here. 

But even breaking line here i cant see why. 

```
cmd := "sonobuoy run --kubeconfig=" + shared.KubeConfigFile +
		" --plugin my-sonobuoy-plugins/mixed-workload-e2e/mixed-workload-e2e.yaml --aggregator-node-selector kubernetes.io/os:linux --wait"
```

You can normally use double quotes

2023-06-28 17:02 UTC, fmoral2 commented
Is this working in a split roles scenario? 

We need to ensure that , since this PR change stuff on the terraform side as well.

2023-06-28 17:39 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +
add documentation

2023-06-28 18:02 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +	}, "120s", "10s").Should(ContainSubstring(ip), fmt.Errorf("failed to validate expected: %s on %s", ip, label))
here fmt.Errorf as optional parameter will potentially cause failures because fmt.Errorf is *errors.errorString  not string.
```
FAILED! Test: Validates internode connectivity over the vxlan tunnel

------------------------------
• [PANICKED] [120.941 seconds]
Test: [It] Validates internode connectivity over the vxlan tunnel
/Users/moral/suse/rke2/tests/acceptance/entrypoint/mixedoscluster/mixedoscluster_test.go:32

  [PANICKED] Test Panicked
  In [It] at: /usr/local/go/src/runtime/iface.go:262 @ 06/28/23 14:59:27.052

  interface conversion: interface {} is *errors.errorString, not string

  Full Stack Trace

```

you can pass directly

`}, "120s", "10s").Should(ContainSubstring(ip), "failed to validate expected: %s on %s", ip, label)`

2023-06-28 18:53 UTC, fmoral2 commented on tests/acceptance/shared/cluster.go
> +func InstallSonobuoy() {
Tips and best practices here:

- Use a "validation" function like returning an error....because u have several places in the code where it an fail

- use idiomatic stuff from the language like :  os.Chmod , os.exec ..... instead of passing directly

example: 

```
func InstallSonobuoy() error {
	scriptsDir := BasePath() + "/acceptance/modules/install/install_sonobuoy.sh"
	fmt.Println(scriptsDir)

	err := os.Chmod(scriptsDir, 0755)
	if err != nil {
		return fmt.Errorf("failed to change script permissions: %v", err)
	}

	cmd := exec.Command("/bin/sh", scriptsDir)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to execute script: %v\nOutput: %s", err, output)
	}

	return nil
}

```

2023-06-28 20:24 UTC, fmoral2 commented on tests/acceptance/core/testcase/cluster.go
> +	fmt.Println("\n***********************************\n")
what do you think change all those prints. to only this ? Since its a costly function

```
	fmt.Println("\n***********************************\n", "Kubeconfig file:\n")
	shared.PrintFileContents(shared.KubeConfigFile)

	fmt.Println("\n***********************************\n", "Base64 Encoded Kubeconfig file:\n")
	shared.PrintBase64Encoded(shared.KubeConfigFile)

	fmt.Println("\n***********************************\n", "Server Node IPS:", cluster.ServerIPs,
		"\n", "Agent Node IPS:", cluster.AgentIPs, "\n", "Windows Agent Node IPS:", cluster.WinAgentIPs)
```

2023-06-28 22:43 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	}, "120s", "3s").Should(ContainSubstring("Welcome to PSTools for K8s Debugging"), fmt.Errorf("failed cmd: %s",cmd))
increase this value a bit please! sometimes it was not enough on my testing

2023-06-28 22:43 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	}, "120s", "3s").Should(ContainSubstring("Welcome to nginx!"), fmt.Errorf("failed cmd: %s",cmd))
increase this value a bit please! sometimes it was not enough on my testing

2023-06-28 23:06 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	shared.ManageWorkload("apply","pod_client.yaml")
you can also if you want change this func `ManageWorkload` to accecpt variadic workloads like 

```
func ManageWorkload(action string , workload ...string)
```

And then pass more than one workload at a time !

2023-06-30 14:32 UTC, fmoral2 commented on tests/acceptance/modules/install/install_sonobuoy.sh
> +#!/bin/bash
the dir already is called `install` no need to call the file as well.

2023-07-05 21:26 UTC, mdrahman-suse commented on tests/acceptance/core/service/factory/cluster.go
> +	NumWinAgents  	int
I prefer having IPs and Num of nodes grouped together.. let me know if that is an issue

2023-07-05 21:29 UTC, mdrahman-suse commented on tests/acceptance/core/service/assert/pod.go
> +		cmd := fmt.Sprintf(`kubectl get pods -l %s -o=jsonpath='{range .items[*]}{.status.podIPs[*].ip}{" "}{end}' --kubeconfig=%s`, label, shared.KubeConfigFile)
I dont see any reference for line exceeding limit but I can make changes to improve the visibility.

2023-07-05 21:30 UTC, mdrahman-suse commented on tests/acceptance/core/service/assert/pod.go
> +		ips :=  strings.Split(res, " ") //e2e.PodIPsUsingLabel(kubeConfigFile, "app=client")
will remove

2023-07-05 21:30 UTC, mdrahman-suse commented on tests/acceptance/core/service/assert/pod.go
> +		return ips[0]
yeah thats how it is being validated on the e2e test

2023-07-05 21:31 UTC, mdrahman-suse commented on tests/acceptance/core/service/factory/cluster.go
> +		WinAgentIPs: WinAgentIPs,
https://github.com/fmoral2/rke2/pull/1#discussion_r1253668053

2023-07-05 21:38 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +	defer func() {
the idea of defer-ring this that it will be executed after it goes the cluster stability check. If that check fails (line 32) it wont even call this func, right?

2023-07-05 21:44 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +	}, "120s", "3s").Should(ContainSubstring("Welcome to PSTools for K8s Debugging"), fmt.Errorf("failed cmd: %s",cmd))
This I got from the e2e, as long as we use the same yaml, it should be fine... if it changes we would know :)

2023-07-05 21:44 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +	fmt.Println(cmd)
will remove

2023-07-05 21:45 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +func testServiceCrossNodeCommunication() {
sure will check that option

2023-07-06 16:33 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +		cmd := fmt.Sprintf(`kubectl get pods -l %s -o=jsonpath='{range .items[*]}{.status.podIPs[*].ip}{" "}{end}' --kubeconfig=%s`, label, shared.KubeConfigFile)
did u run lint? 

``` 
  revive:
    confidence: 0.8
    severity: warning
    ignore-generated-header: true
    rules:
      - name: line-length-limit
        arguments: [110]
      - name: cognitive-complexity
      ```

this is extracted from lint !

2023-07-06 16:34 UTC, fmoral2 commented on tests/acceptance/core/service/factory/cluster.go
> +	NumWinAgents  	int
sure , no p

2023-07-06 16:38 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	}, "120s", "3s").Should(ContainSubstring("Welcome to PSTools for K8s Debugging"), fmt.Errorf("failed cmd: %s",cmd))
This is only a recommendation

 Normally in automated tests you try to assert on stuff that is not likely to change or you minimize the range of this to happen , only asserting in something u are sure that dont usuallu change + returns you confidence that the test pass , because if not u start to have flaky tests in the suite.

i would only recomend to assert like : `  contains("welcome....k8s")..... or contains(welcome) && contains(k8s)  something like thjat

2023-07-10 15:36 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +			g.Expect(pod.Status).Should(Equal(shared.Running), pod.Name)
Here since the only usage of this `shared.Running` we should pass directly as string 
```
			g.Expect(pod.Status).Should(Equal("Running"), pod.Name)
```

2023-07-10 15:36 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +
missing func doc yet.

2023-07-10 15:37 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +		ips :=  strings.Split(res, " ") //e2e.PodIPsUsingLabel(kubeConfigFile, "app=client")
still not removed comment.

2023-07-10 15:38 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +func ValidatePodIPByLabel(label, ip string) {
can we use this func to be more generic ? 

```
func ValidatePodIPByLabel(labels []string, ip string) {
	Eventually(func() error {
		for label := range labels {
			if len(labels) > 0 {
				cmd := fmt.Sprintf(`kubectl get pods -l %s -o=jsonpath='{range .items[*]}{.status.podIPs[*].ip}{" "}{end}' --kubeconfig=%s`,
					labels[label], shared.KubeConfigFile)
				res, _ := shared.RunCommandHost(cmd)
				ips := strings.Split(res, " ")
				if strings.Contains(ips[0], ip) {
					return nil
				}
			}
		}
		return nil
	}, "120s", "10s").Should(Succeed(), "failed to validate expected: %s on %s", ip, labels)
}

```

2023-07-10 15:43 UTC, fmoral2 commented on tests/acceptance/core/testcase/cluster.go
> +	fmt.Println("\n***********************************\n")
still not fixed!

2023-07-10 15:46 UTC, fmoral2 commented on tests/acceptance/core/testcase/daemonset.go
> +		nodes, _ := shared.ParseNodes(false)
same comment from  https://github.com/fmoral2/rke2/pull/1/files#r1258445743

2023-07-10 15:49 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +		nodes, err := shared.ParseNodes(false)
https://github.com/fmoral2/rke2/pull/1/files#r1258445743

2023-07-10 15:52 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +func TestInternodeConnectivityMixedOS(isDefer bool) {
here we are using this defer on the entrypoint ( see other examples there on the `create_cluster_test.go` for 2 reasons:

1 - for exactly avoid usage of control flow boolean as parameter
2 - And to have the ability to manage this more flexible on the calling of the tests.

2023-07-10 15:54 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +// testCrossNodeService Perform testing cross node communication via service exec call
on func docs like that , add a space to be more clear on the reading. 
like that : 

```
// testCrossNodeService Perform testing cross node communication via service exec call
//
// services array Takes service names as parameters in the array
//
// ports	array Takes service ports needed to access the services
//
// expected	array Takes the expected substring from the curl response

2023-07-10 15:55 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	// Iterating services first to last
this for loop dont need this comment since its pretty straightforward that its going increasing , so its first or any position forward.

2023-07-10 15:55 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	// Iterating services last to first
this for loop dont need this comment since its pretty straightforward that its going decreasing  , so its last or any position backwards.

2023-07-10 15:56 UTC, fmoral2 commented on tests/acceptance/core/testcase/pod.go
> +		pods, err := shared.ParsePods(false)
https://github.com/fmoral2/rke2/pull/1/files#r1258445743

2023-07-10 15:58 UTC, fmoral2 commented on tests/acceptance/core/testcase/pod.go
> +				g.Expect(pod.Status).Should(Equal(shared.Completed), pod.Name)
since on this package for now its only use once the assert  "complete " as previous ones lets maintain the pattern, you can pass the string directly

2023-07-10 16:00 UTC, fmoral2 commented on tests/acceptance/core/testcase/upgradecluster.go
> +		shared.Running,
same here

2023-07-10 16:01 UTC, fmoral2 commented on tests/acceptance/entrypoint/createcluster/createcluster_test.go
> +	It("Validate ParseNodes", func() {
https://github.com/fmoral2/rke2/pull/1/files#r1258445743

2023-07-10 16:02 UTC, fmoral2 commented on tests/acceptance/entrypoint/createcluster/createcluster_test.go
> +	It("Validate ParsePods", func() {
https://github.com/fmoral2/rke2/pull/1/files#r1258445743

2023-07-10 16:15 UTC, fmoral2 commented on tests/acceptance/shared/cluster.go
empty extra line here

2023-07-10 16:17 UTC, fmoral2 commented on tests/acceptance/Makefile
> +.PHONY: test-create
test-create-mixedos

2023-07-10 16:18 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +func TestSonobuoyMixedOS() {
missing func doc

2023-07-10 16:20 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	}, "120s", "3s").Should(ContainSubstring("Welcome to PSTools for K8s Debugging"), fmt.Errorf("failed cmd: %s",cmd))
still not fixed.

2023-07-10 16:25 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +//TestInternodeConnectivityMixedOS Deploys services in the cluster and validates communication between linux and windows nodes
// TestInternodeConnectivityMixedOS  

need to add a space on the beggining of the name

2023-07-10 16:26 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	shared.ManageWorkload("apply","pod_client.yaml,windows_app_deployment.yaml")
you need to handle error here.

2023-07-10 16:26 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	testCrossNodeServiceRequest(
you need to handle error here.

2023-07-10 16:28 UTC, fmoral2 commented on tests/acceptance/core/testcase/node.go
> +	shared.InstallSonobuoyMixedOS()
you need to handle error here.

2023-07-10 16:29 UTC, fmoral2 commented on tests/acceptance/core/service/assert/pod.go
> +	}, "120s", "10s").Should(ContainSubstring(ip), fmt.Errorf("failed to validate expected: %s on %s", ip, label))
still not fixed

2023-07-10 16:36 UTC, fmoral2 commented on tests/acceptance/Makefile
> +	@go test -timeout=45m -v ./entrypoint/mixesoscluster/...
typo on mixesoscluster

2023-07-10 17:00 UTC, fmoral2 commented on tests/acceptance/modules/install/install_sonobuoy.sh
> +#!/bin/bash
still not fixed

2023-07-10 17:25 UTC, fmoral2 commented on tests/acceptance/shared/cluster.go
> +func ManageWorkload(action, workloads string) (string, error) {
in here you should use variadic function for some important reasons: 

- function signature ( if you have a signature saying that its parameter is a string, you are willing to confuse who calls this and also not making clear that u can receive slice ) 

- type safety -  if you send a lot of strings as ONE string  as here :  `	shared.ManageWorkload("apply","pod_client.yaml,windows_app_deployment.yaml")`  you are also willing to create ways to whoever calls it making typos or dificulting their life needing to type all workloads as one single string

- simplicity on the function since u will have no need of this : `listOfWorkloads := strings.Split(workloads, ",")`

2023-07-11 18:57 UTC, mdrahman-suse commented on tests/acceptance/core/service/assert/pod.go
> +	}, "120s", "10s").Should(ContainSubstring(ip), fmt.Errorf("failed to validate expected: %s on %s", ip, label))
Updated

2023-07-11 18:57 UTC, mdrahman-suse commented on tests/acceptance/core/service/assert/pod.go
> +func ValidatePodIPByLabel(label string, ip string) {
Updated

2023-07-11 18:57 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +	assert.ValidatePodIPByLabel("app=client","10.42")
Updated

2023-07-11 18:58 UTC, mdrahman-suse commented on tests/acceptance/shared/aux.go
> +func PrintBase64Encoded(filepath string) error {
Updated

2023-07-11 18:58 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +	// Iterating services last to first
Updated

2023-07-11 18:58 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/pod.go
> +				g.Expect(pod.Status).Should(Equal(shared.Running), pod.Name)
Updated

2023-07-11 18:58 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/upgradecluster.go
> +		shared.Running,
Updated

2023-07-11 18:59 UTC, mdrahman-suse commented on tests/acceptance/shared/cluster.go
> +
Updated

2023-07-11 18:59 UTC, mdrahman-suse commented on tests/acceptance/Makefile
> +.PHONY: test-create
Updated

2023-07-11 18:59 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +func TestSonobuoyMixedOS() {
Updated

2023-07-11 18:59 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +//TestInternodeConnectivityMixedOS Deploys services in the cluster and validates communication between linux and windows nodes
Updated

2023-07-11 18:59 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +	shared.ManageWorkload("apply","pod_client.yaml,windows_app_deployment.yaml")
Updated

2023-07-11 19:00 UTC, mdrahman-suse commented on tests/acceptance/core/testcase/node.go
> +	shared.InstallSonobuoyMixedOS()
Updated

2023-07-11 19:00 UTC, mdrahman-suse commented on tests/acceptance/Makefile
> +	@go test -timeout=45m -v ./entrypoint/mixesoscluster/...
Updated

2023-07-11 19:00 UTC, mdrahman-suse commented on tests/acceptance/shared/cluster.go
> +func ManageWorkload(action, workloads string) (string, error) {
Updated

2023-07-11 19:22 UTC, closed without merging